sudo: required

language: c

env:
  global:
    # for the latest public release
    # - GAPCONTAINER="gapsystem/gap-docker"
    # - GAPDIRNAME="gap4r8"
    # for the tests of the stable-4.8 branch
    # - GAPCONTAINER="gapsystem/gap-docker-stable"
    # - GAPDIRNAME="gap-stable-4.8"
    # for the tests of the master branch
    - GAPCONTAINER="gapsystem/gap-docker-master"
    - GAPDIRNAME="gap-master"

  matrix:
    - PKG_NAME=atlasrep # default 6 DIFFS | no pkg 8 DIFFS | all pkg 6 DIFFS
    - PKG_NAME=automgrp # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=ctbllib # default 26 DIFFS | no pkg 26 DIFFS | all pkg 26 DIFFS
    - PKG_NAME=gbnp # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=grpconst # timeout in Travis
    - PKG_NAME=guarana # default 16 DIFFS | no pkg 16 DIFFS | all pkg 16 DIFFS
    - PKG_NAME=hapcryst # default 9 DIFFS | no pkg 9 DIFFS | all pkg 9 DIFFS
    - PKG_NAME=laguna # default 2 DIFFS | no pkg 2 DIFFS | all pkg 2 DIFFS
    - PKG_NAME=lpres # default 21 DIFFS | no pkg 21 DIFFS | all pkg 21 DIFFS
    - PKG_NAME=matgrp # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS
    - PKG_NAME=nq # default 7 DIFFS | no pkg 7 DIFFS | all pkg 7 DIFFS
    - PKG_NAME=polycyclic # default PASS | no pkg PASS | all pkg 2 DIFFS
    - PKG_NAME=polymaking # default 5 DIFFS | no pkg 5 DIFFS | all pkg 5 DIFFS
    - PKG_NAME=profiling # default 1 DIFFS | no pkg 1 DIFFS | all pkg 1 DIFFS

services:
  - docker

before_install:
- docker pull ${GAPCONTAINER}

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"

notifications:
  slack:
    secure: Bsx6lvDTjdfqTpPc+L3788/wIWqIGUK0BYozCN4yXBZh2hHlXaYzViCx2CMOw50MT2JlW/HWn5IihXtqbeRyRtirgiHFDCo/fm2EKZky5ZCZDo7vS18hMd/KdbL8p4uPhEF8ti2Qov6oS1bTnvVIgQM7T4LxOY9qetzz1GAhGkcpWoH8pV1WLy4T1wWzTgSv7mBNU49JFS2knUnQJoPy4GiK43J+bZqPs+cDt78w6HTN8KJx39WxtZnbVZpgsOzPz7CLQMQEVX5oC9jcn3wwIZhCQtfR5PI361jE5IK1tZPk+OL6yfsWDhtc6ovIRfCwjbCp9GpvutI5GuMSt3Kop/8qPQYRvva9eDI1SXfGoJHzPnJtKVb2dUuGzpt8dZrb9n2B3uHYEfQGUzPaKu5DEJXXOPrEy6I3iFZQefah/Ned0YHedmD/rjWJCFSU2zSkLCjj18JocUojFKsmKwe2TU1ZigFJhaOFt7py7QZ1MKYRj1xxro5znCuNFIx9DWy0lskvEAsMLJjs2JBbRgsO+gnXMLMCCii33FShPZyQnQlV0fShe/jHZA+7ueE6fnSnEe+D3Cj9wjge+LCuRLRqnYstM5PEh/a4BZVFLJIj0ZWk9eHBiejKScuOQJ1MVd5pzDqejdeVWC3P+pC376iBELdbN5TwtaEXHFAFc4ts7tE=
