language: c

branches:
  only:
    - master

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-master"

  matrix:
    - PKG_NAME=atlasrep
    - PKG_NAME=automgrp
    - PKG_NAME=cryst
    - PKG_NAME=ctbllib
    - PKG_NAME=ferret
    - PKG_NAME=fr
    - PKG_NAME=gbnp
    - PKG_NAME=groupoids
    - PKG_NAME=hapcryst
    - PKG_NAME=help # see https://github.com/gap-packages/HeLP/issues/3
    - PKG_NAME=openmath
    - PKG_NAME=orb
    - PKG_NAME=packagemanager
    - PKG_NAME=polycyclic
    - PKG_NAME=polymaking
    - PKG_NAME=rcwa
    - PKG_NAME=recog
    - PKG_NAME=simpcomp
    - PKG_NAME=singular
    - PKG_NAME=sla
    - PKG_NAME=sonata
    - PKG_NAME=utils
    - PKG_NAME=xmod

services:
  - docker

before_install:
  - docker pull ${GAPCONTAINER}

script:
  - docker version
  - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"

notifications:
  slack:
    secure: Bsx6lvDTjdfqTpPc+L3788/wIWqIGUK0BYozCN4yXBZh2hHlXaYzViCx2CMOw50MT2JlW/HWn5IihXtqbeRyRtirgiHFDCo/fm2EKZky5ZCZDo7vS18hMd/KdbL8p4uPhEF8ti2Qov6oS1bTnvVIgQM7T4LxOY9qetzz1GAhGkcpWoH8pV1WLy4T1wWzTgSv7mBNU49JFS2knUnQJoPy4GiK43J+bZqPs+cDt78w6HTN8KJx39WxtZnbVZpgsOzPz7CLQMQEVX5oC9jcn3wwIZhCQtfR5PI361jE5IK1tZPk+OL6yfsWDhtc6ovIRfCwjbCp9GpvutI5GuMSt3Kop/8qPQYRvva9eDI1SXfGoJHzPnJtKVb2dUuGzpt8dZrb9n2B3uHYEfQGUzPaKu5DEJXXOPrEy6I3iFZQefah/Ned0YHedmD/rjWJCFSU2zSkLCjj18JocUojFKsmKwe2TU1ZigFJhaOFt7py7QZ1MKYRj1xxro5znCuNFIx9DWy0lskvEAsMLJjs2JBbRgsO+gnXMLMCCii33FShPZyQnQlV0fShe/jHZA+7ueE6fnSnEe+D3Cj9wjge+LCuRLRqnYstM5PEh/a4BZVFLJIj0ZWk9eHBiejKScuOQJ1MVd5pzDqejdeVWC3P+pC376iBELdbN5TwtaEXHFAFc4ts7tE=
